name: api_status
description: Report current status of rk0cc.xyz's API
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.1.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
flutter:
  uses-material-design: true
